namespace SRKSSynergy.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class initial : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.LeadEnquiryRevisedTemp",
                c => new
                    {
                        LERIDPK = c.Int(nullable: false, identity: true),
                        LERID = c.Int(nullable: false),
                        NameofCollector = c.String(),
                        LeadDate = c.DateTime(nullable: false),
                        VisitDate = c.DateTime(nullable: false),
                        MillName = c.String(),
                        MillType = c.String(),
                        AddressLine1 = c.String(),
                        AddressLine2 = c.String(),
                        City = c.String(),
                        Pincode = c.String(),
                        State = c.String(),
                        Country = c.String(),
                        Prefix = c.String(),
                        OwnerName = c.String(),
                        MobNo = c.String(),
                        EmailId = c.String(),
                        Isd = c.String(),
                        Std = c.String(),
                        TelNo = c.String(),
                        EnquiryTypeExistingMill = c.Boolean(nullable: false),
                        EnquiryTypeNewMill = c.Boolean(nullable: false),
                        EnquiryTypeCustomerServiceUpgrade = c.Boolean(nullable: false),
                        TypeOfMillPaddytoRice = c.Boolean(nullable: false),
                        TypeOfMillBrownRiceToWhiteRice = c.Boolean(nullable: false),
                        TypeOfMillReprocess = c.Boolean(nullable: false),
                        TypeOfPaddyProcessLongGrain = c.Boolean(nullable: false),
                        TypeOfPaddyProcessMediumGrain = c.Boolean(nullable: false),
                        TypeOfPaddyProcessRountGrain = c.Boolean(nullable: false),
                        ConditioningRaw = c.Boolean(nullable: false),
                        ConditioningSteamed = c.Boolean(nullable: false),
                        ConditioningParBoiled = c.Boolean(nullable: false),
                        ConditioningParBoiledPaddyMoisture = c.String(),
                        ConditioningParBoiledBulkDensity = c.String(),
                        PaddyVarietyBasmati = c.Boolean(nullable: false),
                        PaddyVarietyNonBasmati = c.Boolean(nullable: false),
                        PaddyVarietyVarietyName = c.String(),
                        EMDProcessingCapacityMill = c.Boolean(nullable: false),
                        EMDProcessingCapacityMillTPH = c.String(),
                        EMDMillOperatingDetailsHoursPerDay = c.String(),
                        PreCleaningCapacity = c.Boolean(nullable: false),
                        TPH2025 = c.Boolean(nullable: false),
                        TPH4050 = c.Boolean(nullable: false),
                        Others = c.Boolean(nullable: false),
                        OthersTPH = c.String(),
                        PaddyStorageMTTotal = c.String(),
                        TotalMT = c.String(),
                        NoOfSilos = c.String(),
                        MillDetailsSuppliersName = c.String(),
                        YearInstalled = c.String(),
                        MillSectionHuller = c.Boolean(nullable: false),
                        MillSectionNos = c.String(),
                        MillSectionKW = c.String(),
                        MillSectionHullSeperate = c.Boolean(nullable: false),
                        MillSectionHullSeperateNos = c.String(),
                        PaddyTable = c.Boolean(nullable: false),
                        PaddyTableNos = c.String(),
                        ThinThickGrader = c.Boolean(nullable: false),
                        ThinThickGraderNos = c.String(),
                        ThinThickGraderDumps = c.String(),
                        Whitner = c.Boolean(nullable: false),
                        WhitnerNos = c.String(),
                        WhitnerKW = c.String(),
                        WhitnerRPM = c.String(),
                        WhitnerYear = c.String(),
                        Polisher = c.Boolean(nullable: false),
                        PolisherNos = c.String(),
                        PolisherKW = c.String(),
                        PolisherRPM = c.String(),
                        PolisherYear = c.String(),
                        LengthGrader = c.Boolean(nullable: false),
                        LengthGraderNos = c.String(),
                        GradeSize1 = c.String(),
                        GradeSize2 = c.String(),
                        GradeSize3 = c.String(),
                        GradeSize4 = c.String(),
                        ColorSorter = c.Boolean(nullable: false),
                        ColorSorterMake = c.String(),
                        ColorSorterChannels = c.String(),
                        ColorSorterPrimary = c.String(),
                        ColorSorterSecondary = c.String(),
                        PackingMachine = c.Boolean(nullable: false),
                        PackingMachineMake = c.String(),
                        PackingMachineNos = c.String(),
                        PackingMachineKgs1 = c.String(),
                        PackingMachineKgs2 = c.String(),
                        PackingMachineBrandName = c.String(),
                        PlantAutomationTypeRelayOrPLCBased = c.Boolean(nullable: false),
                        PlantAutomationTypeRelayOrPLCBasedMake = c.String(),
                        CustomerRequirement1 = c.String(),
                        CustomerRequirement2 = c.String(),
                        CustomerRequirement3 = c.String(),
                        CustomerRequirement4 = c.String(),
                        CustomerRequirement5 = c.String(),
                        CommentsActionExpected = c.String(),
                        CreatedOn = c.DateTime(),
                        CreatedBy = c.String(),
                        ModifiedOn = c.DateTime(),
                        ModifiedBy = c.String(),
                        IsDeleted = c.Int(nullable: false),
                        IsStatus = c.Int(nullable: false),
                        IsDrop = c.Int(nullable: false),
                        CPID = c.Int(nullable: false),
                        LeadTime = c.String(),
                        IsTime = c.Int(nullable: false),
                        IsCount = c.Int(),
                        IsHOD = c.Int(),
                        NotifyDate = c.DateTime(),
                        Latitude = c.String(),
                        Longitude = c.String(),
                        Cleaner = c.Boolean(nullable: false),
                        CleanerNo = c.Int(nullable: false),
                        Magnet = c.Boolean(nullable: false),
                        MagnetNo = c.Int(nullable: false),
                        DeStoner = c.Boolean(nullable: false),
                        DeStonerNo = c.Int(nullable: false),
                        ColorSorter1 = c.Boolean(nullable: false),
                        ColorSorterMake1 = c.String(),
                        ColorSorterChannels1 = c.String(),
                        ColorSorterPrimary1 = c.String(),
                        ColorSorterSecondary1 = c.String(),
                        ColorSorterTertiary = c.String(),
                        ColorSorterTertiary1 = c.String(),
                        CustReqYeorsNo = c.String(),
                        GMCompitator = c.String(),
                        GLCompitator = c.String(),
                        Capacity = c.String(),
                        TypeOfReq = c.String(),
                        MachineClassifier = c.Boolean(nullable: false),
                        MachineDestoner = c.Boolean(nullable: false),
                        MachineHullerSeperator = c.Boolean(nullable: false),
                        MachinePaddySeperator = c.Boolean(nullable: false),
                        MachineThickThinGrader = c.Boolean(nullable: false),
                        MachineWhitner = c.Boolean(nullable: false),
                        MachinePolisher = c.Boolean(nullable: false),
                        MachineSorter = c.Boolean(nullable: false),
                        TimeFrame = c.String(),
                        AssignTo = c.String(),
                        MachineClassifierMTRA = c.Boolean(nullable: false),
                        MachineDestonerMTSC = c.Boolean(nullable: false),
                        MachineScourerMHXF = c.Boolean(nullable: false),
                        MachineAspirationChannelMVSE = c.Boolean(nullable: false),
                        MachineDampenerMOZJ = c.Boolean(nullable: false),
                        MachineDampenerMOZL = c.Boolean(nullable: false),
                        MachineAutomaticMoistureControlMYFE = c.Boolean(nullable: false),
                        MachineRollerMillMDDK = c.Boolean(nullable: false),
                        MachinePurifierMQRF = c.Boolean(nullable: false),
                        PreCleanerClassifierTAS152 = c.Boolean(nullable: false),
                        DrumSieveMKZM9510 = c.Boolean(nullable: false),
                        PreCleanerClassifierLKGA20 = c.Boolean(nullable: false),
                        Huller = c.Boolean(nullable: false),
                        HullerNos = c.String(),
                        HullerKW = c.String(),
                        HullerYear = c.String(),
                        CommodityType = c.String(),
                        EnquiryHandledBy = c.String(),
                        WhitenerSupplierName = c.String(),
                        PolisherSupplierName = c.String(),
                        HullerSupplierName = c.String(),
                        ColorSorterSupplierName = c.String(),
                        ColorSorter1SupplierName = c.String(),
                        QuotesToBeSubmitted = c.String(),
                        ColorSorter1Year = c.String(),
                        ColorSorter2Year = c.String(),
                        SorterModel = c.String(),
                        leadtype = c.String(),
                    })
                .PrimaryKey(t => t.LERIDPK);
            
            AddColumn("dbo.LeadEnquiryRevised", "leadtype", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.LeadEnquiryRevised", "leadtype");
            DropTable("dbo.LeadEnquiryRevisedTemp");
        }
    }
}
